services:
  git2pms-frontend-1:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    networks:
      - pms-network
    depends_on:
      - git2pms-backend-1
    restart: unless-stopped

  git2pms-backend-1:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - pms-network

networks:
  pms-network:
    driver: bridge