
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: shipmgmt
    volumes:
      - mysql_data:/var/lib/mysql
    network_mode: "host"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/shipmgmt?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_APPLICATION_NAME: CrewTaskManagement
      SPRING_PROFILES_ACTIVE: prod
      SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
      SPRING_SQL_INIT_MODE: never
      JWT_SECRET: zi5RGoiqrWBH+aLmBWPPTh9RfarEDFmISiuokYoM+P8=
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:

