services:
  git2pms-frontend-1:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    networks:
      - pms-network
    depends_on:
      - git2pms-backend-1
    restart: unless-stopped

  git2pms-backend-1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://pms-db.cvg40a0wwhxi.ap-northeast-2.rds.amazonaws.com:3306/shipmgmt?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-admin}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-mdt20210616}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_APPLICATION_NAME: CrewTaskManagement
      SPRING_PROFILES_ACTIVE: prod
      SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
      SPRING_SQL_INIT_MODE: always
      JWT_SECRET: zi5RGoiqrWBH+aLmBWPPTh9RfarEDFmISiuokYoM+P8=
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - pms-network

networks:
  pms-network:
    driver: bridge